//
// File generated by rootcint at Sat Oct 28 01:26:39 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME JunDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "JunDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
      #if !(defined(R__ACCESS_IN_SYMBOL) || defined(R__USE_SHADOW_CLASS))
      typedef ::JunArrayOfParticle JunArrayOfParticle;
      #else
      class JunArrayOfParticle  {
         public:
         //friend XX;
         // To force the creation of a virtual table, throw just in case.
         virtual ~JunArrayOfParticle() throw() {};
         ::JunParticle ap[10]; //
         int _num; //
         int _num_he4; //
         int _num_be9; //
         int _code; //
      };
      #endif

   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void JunParticle_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_JunParticle(void *p = 0);
   static void *newArray_JunParticle(Long_t size, void *p);
   static void delete_JunParticle(void *p);
   static void deleteArray_JunParticle(void *p);
   static void destruct_JunParticle(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::JunParticle*)
   {
      ::JunParticle *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::JunParticle >(0);
      static ::ROOT::TGenericClassInfo 
         instance("JunParticle", ::JunParticle::Class_Version(), "./include/JunParticle.hh", 11,
                  typeid(::JunParticle), ::ROOT::DefineBehavior(ptr, ptr),
                  &::JunParticle::Dictionary, isa_proxy, 4,
                  sizeof(::JunParticle) );
      instance.SetNew(&new_JunParticle);
      instance.SetNewArray(&newArray_JunParticle);
      instance.SetDelete(&delete_JunParticle);
      instance.SetDeleteArray(&deleteArray_JunParticle);
      instance.SetDestructor(&destruct_JunParticle);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::JunParticle*)
   {
      return GenerateInitInstanceLocal((::JunParticle*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JunParticle*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

namespace ROOTDict {
   void JunArrayOfParticle_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void JunArrayOfParticle_Dictionary();
   static void *new_JunArrayOfParticle(void *p = 0);
   static void *newArray_JunArrayOfParticle(Long_t size, void *p);
   static void delete_JunArrayOfParticle(void *p);
   static void deleteArray_JunArrayOfParticle(void *p);
   static void destruct_JunArrayOfParticle(void *p);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::JunArrayOfParticle*)
   {
      // Make sure the shadow class has the right sizeof
      R__ASSERT(sizeof(::JunArrayOfParticle) == sizeof( ::ROOTShadow::Shadow::JunArrayOfParticle));
      ::JunArrayOfParticle *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::JunArrayOfParticle),0);
      static ::ROOT::TGenericClassInfo 
         instance("JunArrayOfParticle", "./include/JunArrayOfParticle.hh", 8,
                  typeid(::JunArrayOfParticle), ::ROOT::DefineBehavior(ptr, ptr),
                  &JunArrayOfParticle_ShowMembers, &JunArrayOfParticle_Dictionary, isa_proxy, 4,
                  sizeof(::JunArrayOfParticle) );
      instance.SetNew(&new_JunArrayOfParticle);
      instance.SetNewArray(&newArray_JunArrayOfParticle);
      instance.SetDelete(&delete_JunArrayOfParticle);
      instance.SetDeleteArray(&deleteArray_JunArrayOfParticle);
      instance.SetDestructor(&destruct_JunArrayOfParticle);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::JunArrayOfParticle*)
   {
      return GenerateInitInstanceLocal((::JunArrayOfParticle*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::JunArrayOfParticle*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void JunArrayOfParticle_Dictionary() {
      ::ROOTDict::GenerateInitInstanceLocal((const ::JunArrayOfParticle*)0x0)->GetClass();
   }

} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr JunParticle::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *JunParticle::Class_Name()
{
   return "JunParticle";
}

//______________________________________________________________________________
const char *JunParticle::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::JunParticle*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int JunParticle::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::JunParticle*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void JunParticle::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::JunParticle*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *JunParticle::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::JunParticle*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void JunParticle::Streamer(TBuffer &R__b)
{
   // Stream an object of class JunParticle.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(JunParticle::Class(),this);
   } else {
      R__b.WriteClassBuffer(JunParticle::Class(),this);
   }
}

//______________________________________________________________________________
void JunParticle::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class JunParticle.
      TClass *R__cl = ::JunParticle::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "name", (void*)&name);
      R__insp.InspectMember("string", (void*)&name, "name.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "direction", &direction);
      R__insp.InspectMember(direction, "direction.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "time", &time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "energy", &energy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "theta", &theta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "phi", &phi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "des[3]", des);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "A", &A);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "Z", &Z);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "tflag", &tflag);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "note", (void*)&note);
      R__insp.InspectMember("string", (void*)&note, "note.", false);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_JunParticle(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JunParticle : new ::JunParticle;
   }
   static void *newArray_JunParticle(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JunParticle[nElements] : new ::JunParticle[nElements];
   }
   // Wrapper around operator delete
   static void delete_JunParticle(void *p) {
      delete ((::JunParticle*)p);
   }
   static void deleteArray_JunParticle(void *p) {
      delete [] ((::JunParticle*)p);
   }
   static void destruct_JunParticle(void *p) {
      typedef ::JunParticle current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::JunParticle

//______________________________________________________________________________
namespace ROOTDict {
   void JunArrayOfParticle_ShowMembers(void *obj, TMemberInspector &R__insp)
   {
      // Inspect the data members of an object of class JunArrayOfParticle.
      typedef ::ROOTShadow::Shadow::JunArrayOfParticle ShadowClass;
      ShadowClass *sobj = (ShadowClass*)obj;
      if (sobj) { } // Dummy usage just in case there is no datamember.

      TClass *R__cl  = ::ROOTDict::GenerateInitInstanceLocal((const ::JunArrayOfParticle*)0x0)->GetClass();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ap[10]", sobj->ap);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_num", &sobj->_num);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_num_he4", &sobj->_num_he4);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_num_be9", &sobj->_num_be9);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "_code", &sobj->_code);
   }

}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_JunArrayOfParticle(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JunArrayOfParticle : new ::JunArrayOfParticle;
   }
   static void *newArray_JunArrayOfParticle(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::JunArrayOfParticle[nElements] : new ::JunArrayOfParticle[nElements];
   }
   // Wrapper around operator delete
   static void delete_JunArrayOfParticle(void *p) {
      delete ((::JunArrayOfParticle*)p);
   }
   static void deleteArray_JunArrayOfParticle(void *p) {
      delete [] ((::JunArrayOfParticle*)p);
   }
   static void destruct_JunArrayOfParticle(void *p) {
      typedef ::JunArrayOfParticle current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOTDict for class ::JunArrayOfParticle

/********************************************************
* JunDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableJunDict();

extern "C" void G__set_cpp_environmentJunDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("include/JunArrayOfParticle.hh");
  G__add_compiledheader("include/JunCaliRBR.hh");
  G__add_compiledheader("include/JunErrors.hh");
  G__add_compiledheader("include/JunLossCorrection.hh");
  G__add_compiledheader("include/JunParMan.hh");
  G__add_compiledheader("include/JunParticle.hh");
  G__add_compiledheader("include/reDefine.hh");
  G__cpp_reset_tagtableJunDict();
}
#include <new>
extern "C" int G__cpp_dllrevJunDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* JunParticle */
static int G__JunDict_253_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunParticle* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle[n];
     } else {
       p = new((void*) gvp) JunParticle[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle;
     } else {
       p = new((void*) gvp) JunParticle;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunParticle* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 7:
     //m: 7
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
     }
     break;
   case 6:
     //m: 6
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (int) G__int(libp->para[4]), (int) G__int(libp->para[5]));
     }
     break;
   case 5:
     //m: 5
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (int) G__int(libp->para[4]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3])
, (int) G__int(libp->para[4]));
     }
     break;
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])), (Double_t) G__double(libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, *((TVector3*) G__int(libp->para[2])));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunParticle* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 8:
     //m: 8
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (int) G__int(libp->para[7]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]), (int) G__int(libp->para[7]));
     }
     break;
   case 7:
     //m: 7
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (int) G__int(libp->para[5])
, (int) G__int(libp->para[6]));
     }
     break;
   case 6:
     //m: 6
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (int) G__int(libp->para[5]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]), (int) G__int(libp->para[5]));
     }
     break;
   case 5:
     //m: 5
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3])
, (Double_t) G__double(libp->para[4]));
     }
     break;
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
     } else {
       p = new((void*) gvp) JunParticle(
*((string*) G__int(libp->para[0])), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JunParticle*) G__getstructoffset())->SetNote(*((string*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) JunParticle::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JunParticle::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) JunParticle::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      JunParticle::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const JunParticle*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JunParticle*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JunParticle*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JunParticle*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JunParticle::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JunParticle::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) JunParticle::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_253_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) JunParticle::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JunDict_253_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JunParticle* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JunParticle(*(JunParticle*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JunParticle G__TJunParticle;
static int G__JunDict_253_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JunParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JunParticle*) (soff+(sizeof(JunParticle)*i)))->~G__TJunParticle();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JunParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JunParticle*) (soff))->~G__TJunParticle();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JunDict_253_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunParticle* dest = (JunParticle*) G__getstructoffset();
   *dest = *(JunParticle*) libp->para[0].ref;
   const JunParticle& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* JunArrayOfParticle */
static int G__JunDict_499_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunArrayOfParticle* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunArrayOfParticle[n];
     } else {
       p = new((void*) gvp) JunArrayOfParticle[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new JunArrayOfParticle;
     } else {
       p = new((void*) gvp) JunArrayOfParticle;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((JunArrayOfParticle*) G__getstructoffset())->GetNum((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((JunArrayOfParticle*) G__getstructoffset())->GetNum((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((JunArrayOfParticle*) G__getstructoffset())->GetNum((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *((const string*) G__int(libp->para[2]))));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((JunArrayOfParticle*) G__getstructoffset())->Add(*((JunParticle*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JunArrayOfParticle*) G__getstructoffset())->GetParticle((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JunArrayOfParticle*) G__getstructoffset())->GetParticle((int) G__int(libp->para[0]), (int) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__JunDict_499_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((JunArrayOfParticle*) G__getstructoffset())->GetParticle((int) G__int(libp->para[0]), (int) G__int(libp->para[1])
, *((const string*) G__int(libp->para[2]))));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__JunDict_499_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   JunArrayOfParticle* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new JunArrayOfParticle(*(JunArrayOfParticle*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef JunArrayOfParticle G__TJunArrayOfParticle;
static int G__JunDict_499_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (JunArrayOfParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((JunArrayOfParticle*) (soff+(sizeof(JunArrayOfParticle)*i)))->~G__TJunArrayOfParticle();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (JunArrayOfParticle*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((JunArrayOfParticle*) (soff))->~G__TJunArrayOfParticle();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__JunDict_499_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   JunArrayOfParticle* dest = (JunArrayOfParticle*) G__getstructoffset();
   *dest = *(JunArrayOfParticle*) libp->para[0].ref;
   const JunArrayOfParticle& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* JunParticle */

/* JunArrayOfParticle */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncJunDict {
 public:
  G__Sizep2memfuncJunDict(): p(&G__Sizep2memfuncJunDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncJunDict::*p)();
};

size_t G__get_sizep2memfuncJunDict()
{
  G__Sizep2memfuncJunDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceJunDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableJunDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__JunDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__JunDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<string>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<Par_DSSD>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TSpline2*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TMVA::TSpline2*>",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TMVA::TSpline2*,less<string> >",117,G__get_linked_tagnum(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<sInfo>",117,G__get_linked_tagnum(&G__JunDictLN_vectorlEsInfocOallocatorlEsInfogRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEsInfocOallocatorlEsInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEsInfocOallocatorlEsInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__JunDictLN_reverse_iteratorlEvectorlEsInfocOallocatorlEsInfogRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__JunDictLN_vectorlEsInfocOallocatorlEsInfogRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string>",117,G__get_linked_tagnum(&G__JunDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<int,string,less<int> >",117,G__get_linked_tagnum(&G__JunDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* JunParticle */
static void G__setup_memvarJunParticle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   { JunParticle *p; p=(JunParticle*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->name)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__JunDictLN_string),-1,-1,1,"name=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->direction)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__JunDictLN_TVector3),-1,-1,1,"direction=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->time)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"time=",0,"channel of tdc");
   G__memvar_setup((void*)((long)(&p->energy)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"energy=",0,"*MeV");
   G__memvar_setup((void*)((long)(&p->theta)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"theta=",0,"*deg");
   G__memvar_setup((void*)((long)(&p->phi)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"phi=",0,"*deg");
   G__memvar_setup((void*)((long)(&p->des)-(long)(p)),100,0,0,-1,G__defined_typename("Double_t"),-1,1,"des[3]=",0,"energy on different Detectors *MeV");
   G__memvar_setup((void*)((long)(&p->A)-(long)(p)),105,0,0,-1,-1,-1,1,"A=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->Z)-(long)(p)),105,0,0,-1,-1,-1,1,"Z=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->tflag)-(long)(p)),105,0,0,-1,-1,-1,1,"tflag=",0,"l1:1000 l0:100 r0:10 r1:1");
   G__memvar_setup((void*)((long)(&p->note)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__JunDictLN_string),-1,-1,1,"note=",0,"He4 : t0ssd/t0bb7/t1ssd ; Be9 : t0recoil/t0break/t1more");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__JunDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* JunArrayOfParticle */
static void G__setup_memvarJunArrayOfParticle(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle));
   { JunArrayOfParticle *p; p=(JunArrayOfParticle*)0x1000; if (p) { }
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->ap)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__JunDictLN_JunParticle),-1,-1,1,"ap[10]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_num)-(long)(p)),105,0,0,-1,-1,-1,1,"_num=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_num_he4)-(long)(p)),105,0,0,-1,-1,-1,1,"_num_he4=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_num_be9)-(long)(p)),105,0,0,-1,-1,-1,1,"_num_be9=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->_code)-(long)(p)),105,0,0,-1,-1,-1,1,"_code=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarJunDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncJunParticle(void) {
   /* JunParticle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JunDictLN_JunParticle));
   G__memfunc_setup("JunParticle",1121,G__JunDict_253_0_1, 105, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JunParticle",1121,G__JunDict_253_0_2, 105, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 7, 1, 1, 0, 
"u 'string' - 0 - pName d - 'Double_t' 0 - pEnergy "
"u 'TVector3' - 0 - pDirection d - 'Double_t' 0 '-99999' pTime "
"i - - 0 '0' a i - - 0 '0' z "
"i - - 0 '0' tele", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("JunParticle",1121,G__JunDict_253_0_3, 105, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 8, 1, 1, 0, 
"u 'string' - 0 - pName d - 'Double_t' 0 - pEnergy "
"d - 'Double_t' 0 - pTheta d - 'Double_t' 0 - pPhi "
"d - 'Double_t' 0 '-99999' pTime i - - 0 '0' a "
"i - - 0 '0' z i - - 0 '0' tele", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNote",706,G__JunDict_253_0_4, 121, -1, -1, 0, 1, 1, 1, 0, "u 'string' - 0 - tNote", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__JunDict_253_0_5, 85, G__get_linked_tagnum(&G__JunDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&JunParticle::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__JunDict_253_0_6, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JunParticle::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__JunDict_253_0_7, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&JunParticle::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__JunDict_253_0_8, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&JunParticle::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__JunDict_253_0_9, 85, G__get_linked_tagnum(&G__JunDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__JunDict_253_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__JunDict_253_0_11, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__JunDict_253_0_12, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__JunDict_253_0_13, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JunParticle::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__JunDict_253_0_14, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JunParticle::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__JunDict_253_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&JunParticle::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__JunDict_253_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&JunParticle::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("JunParticle", 1121, G__JunDict_253_0_17, (int) ('i'), G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 1, 1, 1, 0, "u 'JunParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JunParticle", 1247, G__JunDict_253_0_18, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JunDict_253_0_19, (int) ('u'), G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 1, 1, 1, 1, 0, "u 'JunParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncJunArrayOfParticle(void) {
   /* JunArrayOfParticle */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle));
   G__memfunc_setup("JunArrayOfParticle",1813,G__JunDict_499_0_1, 105, G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNum",592,G__JunDict_499_0_2, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - Z i - - 0 - A "
"i - - 0 - tele", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNum",592,G__JunDict_499_0_3, 105, -1, -1, 0, 2, 1, 1, 0, 
"i - - 0 - Z i - - 0 - A", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNum",592,G__JunDict_499_0_4, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - Z i - - 0 - A "
"u 'string' - 10 - note", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Add",265,G__JunDict_499_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "u 'JunParticle' - 0 - tp", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParticle",1108,G__JunDict_499_0_6, 85, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 3, 1, 1, 0, 
"i - - 0 - Z i - - 0 - A "
"i - - 0 - tele", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParticle",1108,G__JunDict_499_0_7, 85, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 2, 1, 1, 0, 
"i - - 0 - Z i - - 0 - A", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetParticle",1108,G__JunDict_499_0_8, 85, G__get_linked_tagnum(&G__JunDictLN_JunParticle), -1, 0, 3, 1, 1, 0, 
"i - - 0 - Z i - - 0 - A "
"u 'string' - 10 - note", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("JunArrayOfParticle", 1813, G__JunDict_499_0_9, (int) ('i'), G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle), -1, 0, 1, 1, 1, 0, "u 'JunArrayOfParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~JunArrayOfParticle", 1939, G__JunDict_499_0_10, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__JunDict_499_0_11, (int) ('u'), G__get_linked_tagnum(&G__JunDictLN_JunArrayOfParticle), -1, 1, 1, 1, 1, 0, "u 'JunArrayOfParticle' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncJunDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalJunDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcJunDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__JunDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__JunDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__JunDictLN_JunParticle = { "JunParticle" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR = { "vector<string,allocator<string> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<string,allocator<string> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR = { "vector<Par_DSSD,allocator<Par_DSSD> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<Par_DSSD,allocator<Par_DSSD> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_JunArrayOfParticle = { "JunArrayOfParticle" , 99 , -1 };
G__linked_taginfo G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR = { "map<string,TMVA::TSpline2*,less<string>,allocator<pair<const string,TMVA::TSpline2*> > >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_vectorlEsInfocOallocatorlEsInfogRsPgR = { "vector<sInfo,allocator<sInfo> >" , 99 , -1 };
G__linked_taginfo G__JunDictLN_reverse_iteratorlEvectorlEsInfocOallocatorlEsInfogRsPgRcLcLiteratorgR = { "reverse_iterator<vector<sInfo,allocator<sInfo> >::iterator>" , 99 , -1 };
G__linked_taginfo G__JunDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR = { "map<int,string,less<int>,allocator<pair<const int,string> > >" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableJunDict() {
  G__JunDictLN_TClass.tagnum = -1 ;
  G__JunDictLN_TBuffer.tagnum = -1 ;
  G__JunDictLN_TMemberInspector.tagnum = -1 ;
  G__JunDictLN_string.tagnum = -1 ;
  G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__JunDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__JunDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__JunDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__JunDictLN_TVector3.tagnum = -1 ;
  G__JunDictLN_JunParticle.tagnum = -1 ;
  G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_JunArrayOfParticle.tagnum = -1 ;
  G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR.tagnum = -1 ;
  G__JunDictLN_vectorlEsInfocOallocatorlEsInfogRsPgR.tagnum = -1 ;
  G__JunDictLN_reverse_iteratorlEvectorlEsInfocOallocatorlEsInfogRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__JunDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableJunDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__JunDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__JunDictLN_string);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_TVector3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JunDictLN_JunParticle),sizeof(JunParticle),-1,296192,(char*)NULL,G__setup_memvarJunParticle,G__setup_memfuncJunParticle);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEstringcOallocatorlEstringgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEstringcOallocatorlEstringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEPar_DSSDcOallocatorlEPar_DSSDgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__JunDictLN_JunArrayOfParticle),sizeof(JunArrayOfParticle),-1,263424,(char*)NULL,G__setup_memvarJunArrayOfParticle,G__setup_memfuncJunArrayOfParticle);
   G__get_linked_tagnum_fwd(&G__JunDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_maplEstringcOTMVAcLcLTSpline2mUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTMVAcLcLTSpline2mUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_vectorlEsInfocOallocatorlEsInfogRsPgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_reverse_iteratorlEvectorlEsInfocOallocatorlEsInfogRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__JunDictLN_maplEintcOstringcOlesslEintgRcOallocatorlEpairlEconstsPintcOstringgRsPgRsPgR);
}
extern "C" void G__cpp_setupJunDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupJunDict()");
  G__set_cpp_environmentJunDict();
  G__cpp_setup_tagtableJunDict();

  G__cpp_setup_inheritanceJunDict();

  G__cpp_setup_typetableJunDict();

  G__cpp_setup_memvarJunDict();

  G__cpp_setup_memfuncJunDict();
  G__cpp_setup_globalJunDict();
  G__cpp_setup_funcJunDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncJunDict();
  return;
}
class G__cpp_setup_initJunDict {
  public:
    G__cpp_setup_initJunDict() { G__add_setup_func("JunDict",(G__incsetup)(&G__cpp_setupJunDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initJunDict() { G__remove_setup_func("JunDict"); }
};
G__cpp_setup_initJunDict G__cpp_setup_initializerJunDict;

